"""
NPT Fleet Tools: Cloud Storage (GCS) Management
Architecture: Google Cloud Storage Client (Native Ecosystem Containment)
"""
import os
from google.cloud import storage

# =====================================================================
# INTERNAL HELPER FUNCTIONS (Not directly callable by Agents)
# =====================================================================

def _get_bucket():
    """
    Internal Helper: GCS Perimeter Connector.
    Purpose: Initializes the Google Cloud Storage bucket connection using ambient 
    enterprise credentials. Defaults to 'npt-fleet-cargo-hold'.
    Invoked By: Called internally by all cloud storage tools.
    """
    bucket_name = os.getenv("GCP_BUCKET_NAME", "npt-fleet-cargo-hold")
    client = storage.Client()
    return client.bucket(bucket_name)


# =====================================================================
# AGENT TOOLS (Exposed via tool_dispatcher.py)
# =====================================================================

def list_knowledge_artifacts() -> str:
    """
    Agent Tool: GCS Directory Listing.
    Purpose: Lists all persistent forensic documents currently held in the cloud bucket.
    Invoked By: General diagnostic tool available to multiple agents if they need to verify 
    the presence of an artifact in the Cargo Hold.
    """
    try:
        bucket = _get_bucket()
        blobs = bucket.list_blobs()
        names = [blob.name for blob in blobs]
        
        if not names:
            return "[NOTICE] The cloud cargo hold is currently empty."
            
        return "Cloud Knowledge Artifacts:\n" + "\n".join([f"- {name}" for name in names])
    except Exception as e:
        return f"[ERROR] Failed to read GCS bucket: {str(e)}"


def read_knowledge_artifact(artifact_name: str) -> str:
    """
    Agent Tool: The Bronze Text Extractor.
    Purpose: Downloads the exact verbatim text of a specified knowledge artifact 
    from the GCS bucket into the agent's context window for analysis.
    Invoked By: CUTLASS (Epistemic Auditor), GROG (Structural Extraction), 
    PLANK (Ontology Mapping), and BILGELADLE (Thesis Alignment).
    """
    try:
        bucket = _get_bucket()
        blob = bucket.blob(artifact_name)
        
        if not blob.exists():
            return f"[ERROR] Artifact '{artifact_name}' not found."
            
        return blob.download_as_text(encoding="utf-8")
    except Exception as e:
        return f"[ERROR] Failed to read artifact: {str(e)}"


def upsert_knowledge_artifact(artifact_name: str, content: str = "", local_cache_path: str = "") -> str:
    """
    Agent Tool: The Cargo Uploader & Cache Clearer.
    Purpose: Streams the extracted payload into the cloud cargo hold. 
    Crucially, it handles the token-saving mechanism by accepting a 'local_cache_path' 
    (generated by download_url). It reads the massive text file from the local disk, 
    uploads it to GCS, and immediately deletes the local temp file to keep the sandbox clean.
    Invoked By: SPYGLASS (The Ingestion Engine).
    """
    try:
        upload_string = content
        
        # Determine if the payload is a direct string or a file pointer from the local cache
        target_path = local_cache_path
        if content and isinstance(content, str) and os.path.exists(content) and content.endswith(".txt"):
            target_path = content

        # Read the file and clean up the temp cache
        if target_path and os.path.exists(target_path):
            with open(target_path, 'r', encoding='utf-8') as f:
                upload_string = f.read()
            os.remove(target_path) 
            
        if not upload_string:
            return "[ERROR] No content or valid local_cache_path provided."

        # ACTUAL GCP UPLOAD LOGIC
        bucket = _get_bucket()
        blob = bucket.blob(artifact_name)
        blob.upload_from_string(upload_string, content_type="text/plain; charset=utf-8")
        
        return f"[SUCCESS] Knowledge artifact successfully uploaded to {artifact_name}"
        
    except Exception as e:
        return f"[ERROR] Upload stream rejected: {str(e)}"