"""
NPT Fleet: Silver Ledger Schema & Permission Builder
Description: Creates the ship.letters_of_marque table and explicitly maps 
application user permissions.
CRITICAL TEMPLATE FOR HOOK: Any future DB provisioning scripts generated by Hook 
MUST include the exact 'GRANT' privilege block shown in Step 2 of this script.
"""
import os
from urllib.parse import urlparse
import pg8000.dbapi
from dotenv import load_dotenv

load_dotenv()

def build_memory_table():
    # Targets the content/cargo database
    conn_string = os.getenv("CONTENT_DATABASE_URL")
    root_password = os.getenv("DB_ROOT_PASSWORD")
    
    if not conn_string or not root_password:
        print("[FATAL] Missing credentials in .env")
        return

    url = urlparse(conn_string)
    app_user = url.username
    db_name = url.path[1:]
    host = url.hostname
    port = url.port

    try:
        print(f"Connecting to {db_name} as root to build ship.letters_of_marque...")
        # Connecting as 'postgres' (root) to execute structural changes
        conn = pg8000.dbapi.connect(
            user="postgres", password=root_password, host=host, port=port, database=db_name
        )
        conn.autocommit = True
        cursor = conn.cursor()

        # 1. Structural Definition (CREATE)        
        cursor.execute("""
-- 1. Enable the pgvector extension globally
CREATE EXTENSION IF NOT EXISTS vector;

-- 2. Create the unified crew asset schema
CREATE SCHEMA IF NOT EXISTS ship;

-- 3. Provision the letters_of_marque table
CREATE TABLE IF NOT EXISTS ship.letters_of_marque (
    -- The deterministic unique key (e.g., 'ch7_sec7-3_p4')
    chunk_id VARCHAR(50) PRIMARY KEY,              
    
    chapter_number INT NOT NULL,
    section_number VARCHAR(10) NOT NULL,
    header_title TEXT NOT NULL,
    
    -- Absolute sequential position of this paragraph within the entire book
    book_sequence_number INT NOT NULL,             
    
    -- Sequential position of this paragraph within this specific section
    paragraph_sequence_number INT NOT NULL,        
    
    -- The actual human-readable prose
    chunk_text TEXT NOT NULL,                      
    
    -- Optional vector representation (Gemini Text-Embedding-004)
    vector_embedding vector(1536),                 
    
    -- Immutable GCS path to the parent Silver Section markdown file
    parent_gcs_pointer TEXT NOT NULL,              
    
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 4. Create index on the vector column
CREATE INDEX IF NOT EXISTS letters_of_marque_vector_idx 
ON ship.letters_of_marque 
USING hnsw (vector_embedding vector_cosine_ops);

-- 5. Create index for fast structured sequencing and reading
CREATE INDEX IF NOT EXISTS letters_of_marque_flow_idx 
ON ship.letters_of_marque (book_sequence_number);
        """)
        print("[SUCCESS] Table 'ship.letters_of_marque' created.")

        # 2. The Permission Handoff (GRANT) - MANDATORY FOR ALL DB CREATION SCRIPTS
        # Because 'postgres' created the table, the 'app_user' cannot use it without these lines.
        cursor.execute(f"GRANT USAGE, CREATE ON SCHEMA ship TO {app_user};")
        cursor.execute(f"GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA ship TO {app_user};")
        cursor.execute(f"GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA ship TO {app_user};")
        print(f"[SUCCESS] Privileges explicitly mapped to '{app_user}'.")

        cursor.close()
        conn.close()
        print("\n[DEPLOYMENT COMPLETE] ship.letters_of_marque is online.")

    except Exception as e:
        print(f"\n[FATAL ERROR] {e}")

if __name__ == "__main__":
    build_memory_table()