[project]
name = "npt-knowing-2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "google-cloud-storage>=3.10.1",
    "google-genai>=2.7.0",
    "httpx>=0.28.1",
    "langchain-core>=1.4.0",
    "pypdf>=6.12.2",
    "python-dotenv>=1.2.2",
    "pyzotero>=1.13.0",
    "trafilatura>=2.0.0",
]
